### PR TITLE
modify custom user handshake function to be able to do more work.

### PR DESCRIPTION
**Pull request by mog422**

### CODE REVIEW

**Comment by cynron** [comment]
This PR changes the  `this` reference within `userHandshake` from `Command`-self to argument `socket`, so why does it matter?

**Comment by mog422** [comment]
I think that Command is useless in userHandshake function.

**Comment by cynron** [comment]
@mog422 I prefer to this PR, but it breaks API compatibility.

/cc @py8765

**Comment by mog422** [comment]
@cynron Hum.. So... What about move ```socket``` to second argument or last argument?

**Comment by mog422** [comment]
This commit does not break API compatibility any more.

**Comment by cynron** [comment]
landed f1651c3f554cc8d2c4c8c71f805b8e925af68587 , thanks!

**Pull request closed without merging**
